name: 'Conventional Changelog Action'
on:
  push
jobs:

  changelog:
    runs-on: ubuntu-latest
    steps:
        - uses: TriPSs/conventional-changelog-action@v3.18.0
          with:
            github-token: ${{ secrets.github_token }}
            output-file: "false"
